// AUTO-GENERATED by orpc — do not edit manually.
// Re-generate: orpc::generate_contract().output(path)

import { z } from "zod";
import { oc } from "@orpc/contract";
import { openapi } from "@orpc/openapi";
import { asyncIteratorObject } from "@orpc/contract";

export const CreatePlanetInputSchema = z.object({
  name: z.string(),
  description: z.string().optional()
});

export type CreatePlanetInput = z.infer<typeof CreatePlanetInputSchema>;

export const PlanetSchema = z.object({
  id: z.number().int(),
  name: z.string(),
  description: z.string().optional()
});

export type Planet = z.infer<typeof PlanetSchema>;

export const ListPlanetsPaginatedOutputSchema = z.object({
  items: z.array(PlanetSchema),
  next_page_param: z.number().int().optional()
});

export type ListPlanetsPaginatedOutput = z.infer<typeof ListPlanetsPaginatedOutputSchema>;

export const ListPlanetsPaginatedInputSchema = z.object({
  limit: z.number().int(),
  offset: z.number().int().optional()
});

export type ListPlanetsPaginatedInput = z.infer<typeof ListPlanetsPaginatedInputSchema>;

export const StreamEventSchema = z.object({
  message: z.string(),
  count: z.number().int()
});

export type StreamEvent = z.infer<typeof StreamEventSchema>;

export const FindPlanetInputSchema = z.object({
  id: z.number().int()
});

export type FindPlanetInput = z.infer<typeof FindPlanetInputSchema>;

export const contract = {
  streamEventsAsync: oc
      .meta(openapi({ method: "GET", path: "/stream-async" }))
      .output(asyncIteratorObject(StreamEventSchema)),
  streamEvents: oc
      .meta(openapi({ method: "GET", path: "/stream" }))
      .output(asyncIteratorObject(StreamEventSchema)),
  ping: oc
      .meta(openapi({ method: "POST", path: "/ping" }))
      .output(z.string()),
  getProfile: oc
      .meta(openapi({ method: "POST", path: "/profile" }))
      .output(z.any()),
  planet: {
    createPlanet: oc
      .meta(openapi({ method: "POST", path: "/planet/create" }))
      .input(CreatePlanetInputSchema)
      .output(PlanetSchema)
      .errors({
        NOT_FOUND: {},
        BAD_REQUEST: {
          data: z.object({ reason: z.string() })
        },
        INTERNAL: {
          data: z.string()
        },
        UNAUTHORIZED: {}
      }),
    findPlanet: oc
      .meta(openapi({ method: "POST", path: "/planet/find" }))
      .input(FindPlanetInputSchema)
      .output(PlanetSchema)
      .errors({
        NOT_FOUND: {},
        BAD_REQUEST: {
          data: z.object({ reason: z.string() })
        },
        INTERNAL: {
          data: z.string()
        },
        UNAUTHORIZED: {}
      }),
    listPlanetsPaginated: oc
      .meta(openapi({ method: "POST", path: "/planet/list-paginated" }))
      .input(ListPlanetsPaginatedInputSchema)
      .output(ListPlanetsPaginatedOutputSchema)
      .errors({
        NOT_FOUND: {},
        BAD_REQUEST: {
          data: z.object({ reason: z.string() })
        },
        INTERNAL: {
          data: z.string()
        },
        UNAUTHORIZED: {}
      }),
    listPlanets: oc
      .meta(openapi({ method: "POST", path: "/planet/list" }))
      .output(z.array(PlanetSchema))
      .errors({
        NOT_FOUND: {},
        BAD_REQUEST: {
          data: z.object({ reason: z.string() })
        },
        INTERNAL: {
          data: z.string()
        },
        UNAUTHORIZED: {}
      }),
  },
} as const;

export type Contract = typeof contract;