// AUTO-GENERATED by rorpc — do not edit manually.
// Re-generate: rorpc::generate_contract().output(path)

import { z } from "zod";
import { oc } from "@orpc/contract";
import { openapi } from "@orpc/openapi";
import { asyncIteratorObject } from "@orpc/contract";

export const StreamEventSchema = z.object({
  message: z.string(),
  count: z.number().int()
});

export type StreamEvent = z.infer<typeof StreamEventSchema>;

export const ListPlanetsPaginatedInputSchema = z.object({
  limit: z.number().int(),
  offset: z.number().int().optional()
});

export type ListPlanetsPaginatedInput = z.infer<typeof ListPlanetsPaginatedInputSchema>;

export const DeletePlanetInputSchema = z.object({
  id: z.number().int()
});

export type DeletePlanetInput = z.infer<typeof DeletePlanetInputSchema>;

export const FindPlanetInputSchema = z.object({
  id: z.number().int()
});

export type FindPlanetInput = z.infer<typeof FindPlanetInputSchema>;

export const CreatePlanetInputSchema = z.object({
  name: z.string(),
  description: z.string().optional()
});

export type CreatePlanetInput = z.infer<typeof CreatePlanetInputSchema>;

export const PlanetSchema = z.object({
  id: z.number().int(),
  name: z.string(),
  description: z.string().optional()
});

export type Planet = z.infer<typeof PlanetSchema>;

export const ListPlanetsPaginatedOutputSchema = z.object({
  items: z.array(PlanetSchema),
  next_page_param: z.number().int().optional()
});

export type ListPlanetsPaginatedOutput = z.infer<typeof ListPlanetsPaginatedOutputSchema>;

export const contract = {
  streamEventsAsync: oc
      .meta(openapi({ method: "GET", path: "/stream-async" }))
      .output(asyncIteratorObject(StreamEventSchema)),
  streamEvents: oc
      .meta(openapi({ method: "GET", path: "/stream" }))
      .output(asyncIteratorObject(StreamEventSchema)),
  ping: oc
      .meta(openapi({ method: "GET", path: "/ping" }))
      .output(z.string()),
  getProfile: oc
      .meta(openapi({ method: "GET", path: "/profile" }))
      .output(z.any()),
  planet: {
    deletePlanet: oc
      .meta(openapi({ method: "DELETE", path: "/planet/delete" }))
      .input(DeletePlanetInputSchema)
      .errors({
        NOT_FOUND: {},
        INTERNAL: {
          data: z.object({ msg: z.string() })
        }
      }),
    createPlanet: oc
      .meta(openapi({ method: "POST", path: "/planet/create" }))
      .input(CreatePlanetInputSchema)
      .output(PlanetSchema)
      .errors({
        NOT_FOUND: {},
        INTERNAL: {
          data: z.object({ msg: z.string() })
        }
      }),
    findPlanet: oc
      .meta(openapi({ method: "GET", path: "/planet/find" }))
      .input(FindPlanetInputSchema)
      .output(PlanetSchema)
      .errors({
        NOT_FOUND: {},
        INTERNAL: {
          data: z.object({ msg: z.string() })
        }
      }),
    listPlanetsPaginated: oc
      .meta(openapi({ method: "GET", path: "/planet/list-paginated" }))
      .input(ListPlanetsPaginatedInputSchema)
      .output(ListPlanetsPaginatedOutputSchema)
      .errors({
        NOT_FOUND: {},
        INTERNAL: {
          data: z.object({ msg: z.string() })
        }
      }),
    listPlanets: oc
      .meta(openapi({ method: "GET", path: "/planet/list" }))
      .output(z.array(PlanetSchema))
      .errors({
        NOT_FOUND: {},
        INTERNAL: {
          data: z.object({ msg: z.string() })
        }
      }),
  },
} as const;

export type Contract = typeof contract;