// AUTO-GENERATED by orpc — do not edit manually.
// Re-generate: orpc::generate_contract().output(path)

import { z } from "zod";
import { oc } from "@orpc/contract";
import { openapi } from "@orpc/openapi";
import { asyncIteratorObject } from "@orpc/contract";

export const PlanetSchema = z.object({
  id: z.number().int(),
  name: z.string(),
  description: z.string().optional()
});

export type Planet = z.infer<typeof PlanetSchema>;

export const CreatePlanetInputSchema = z.object({
  name: z.string(),
  description: z.string().optional()
});

export type CreatePlanetInput = z.infer<typeof CreatePlanetInputSchema>;

export const FindPlanetInputSchema = z.object({
  id: z.number().int()
});

export type FindPlanetInput = z.infer<typeof FindPlanetInputSchema>;

export const contract = {
  ping: oc
      .meta(openapi({ method: "GET", path: "/ping" }))
      .output(z.string()),
  planet: {
    createPlanet: oc
      .meta(openapi({ method: "POST", path: "/planet/create" }))
      .input(CreatePlanetInputSchema)
      .output(PlanetSchema),
    findPlanet: oc
      .meta(openapi({ method: "POST", path: "/planet/find" }))
      .input(FindPlanetInputSchema)
      .output(PlanetSchema),
    listPlanets: oc
      .meta(openapi({ method: "POST", path: "/planet/list" }))
      .output(z.array(PlanetSchema)),
  },
} as const;

export type Contract = typeof contract;