// AUTO-GENERATED by orpc — do not edit manually.
// Re-generate with: cargo run --bin axum-native
// Or with: orpc::generate_contract().output("client/src/rpc/index.ts")

// This file will be populated automatically when the server starts in dev mode.
// See examples/axum-native/src/main.rs
