//! TypeScript contract and Zod schema generation for orpc.
//!
//! Produces a TypeScript file containing:
//! - Zod schema constants for each input/output type (from `ZodTs::zod_ts()`)
//! - An oRPC `contract` object matching the Rust handler structure
//! - Type exports (`export type X = z.infer<typeof XSchema>`)
//!
//! This crate is pure functions — no Axum, no proc-macros, fully testable.

pub mod contract;
pub mod typescript;

use std::path::Path;

/// Metadata for a single handler passed from `orpc::generate_contract()`.
#[derive(Debug, Clone)]
pub struct HandlerInfo {
    pub name: &'static str,
    pub method: &'static str,
    pub path: &'static str,
    pub input_type_name: &'static str,
    pub output_type_name: &'static str,
    pub module_path: &'static str,
}

/// A collected Zod schema string for a single Rust type.
///
/// Produced by calling `T::zod_ts()` via the registered factory fn.
#[derive(Debug, Clone)]
pub struct SchemaEntry {
    /// Rust type name — used for deduplication and matching against handler types
    pub type_name: &'static str,
    /// Full TypeScript schema string produced by `ZodTs::zod_ts()`
    ///
    /// Example:
    /// ```typescript
    /// export const PlanetSchema = z.object({
    ///   id: z.number().int(),
    ///   name: z.string(),
    ///   description: z.string().optional(),
    /// });
    /// export type Planet = z.infer<typeof PlanetSchema>;
    /// ```
    pub zod_ts: String,
}

/// Builder for TypeScript contract generation.
///
/// # Example
///
/// ```rust,ignore
/// ContractBuilder::new(handlers, schemas)
///     .output("../client/src/rpc/index.ts")
///     .unwrap();
/// ```
pub struct ContractBuilder {
    handlers: Vec<HandlerInfo>,
    /// Real Zod schema strings from `ZodTs::zod_ts()` — empty if no types registered
    schemas: Vec<SchemaEntry>,
}

impl ContractBuilder {
    pub fn new(handlers: Vec<HandlerInfo>, schemas: Vec<SchemaEntry>) -> Self {
        Self { handlers, schemas }
    }

    /// Generate the TypeScript contract and write it to `path`.
    ///
    /// Rejects paths containing `..` components to prevent path traversal.
    pub fn output(self, path: impl AsRef<Path>) -> std::io::Result<()> {
        let path = path.as_ref();

        // Security: reject path traversal (A03)
        for component in path.components() {
            if component.as_os_str() == ".." {
                return Err(std::io::Error::new(
                    std::io::ErrorKind::InvalidInput,
                    "output path must not contain '..' components",
                ));
            }
        }

        let content = self.generate();

        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }

        std::fs::write(path, content)
    }

    /// Generate the full TypeScript content as a string.
    pub fn generate(self) -> String {
        let imports = typescript::generate_imports();
        let schemas = if self.schemas.is_empty() {
            // Fallback: placeholder schemas from type names
            typescript::generate_placeholder_schemas(&self.handlers)
        } else {
            // Real schemas from ZodTs::zod_ts()
            typescript::generate_real_schemas(&self.schemas)
        };
        let contract = contract::generate_contract(&self.handlers);

        format!(
            "// AUTO-GENERATED by orpc — do not edit manually.\n// Re-generate: orpc::generate_contract().output(path)\n\n{imports}\n\n{schemas}\n\n{contract}"
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_handler(name: &'static str, method: &'static str, path: &'static str) -> HandlerInfo {
        HandlerInfo {
            name,
            method,
            path,
            input_type_name: "()",
            output_type_name: "String",
            module_path: "test::handlers",
        }
    }

    #[test]
    fn rejects_path_traversal() {
        let builder = ContractBuilder {
            handlers: vec![make_handler("ping", "GET", "/ping")],
            schemas: vec![],
        };
        let result = builder.output("../../../etc/passwd");
        assert!(result.is_err());
        assert!(result.unwrap_err().kind() == std::io::ErrorKind::InvalidInput);
    }

    #[test]
    fn generates_with_no_schemas() {
        let builder = ContractBuilder {
            handlers: vec![make_handler("ping", "GET", "/ping")],
            schemas: vec![],
        };
        let output = builder.generate();
        assert!(output.contains("AUTO-GENERATED"));
        assert!(output.contains("ping"));
    }

    #[test]
    fn generates_with_real_schemas() {
        let builder = ContractBuilder {
            handlers: vec![make_handler("list_planets", "POST", "/planet/list")],
            schemas: vec![SchemaEntry {
                type_name: "Planet",
                zod_ts: "export const PlanetSchema = z.object({ id: z.number().int(), name: z.string() });\nexport type Planet = z.infer<typeof PlanetSchema>;".to_string(),
            }],
        };
        let output = builder.generate();
        assert!(output.contains("PlanetSchema"));
        assert!(output.contains("z.object"));
        assert!(output.contains("listPlanets"));
    }
}
