//! TypeScript contract and Zod schema generation for orpc.
//!
//! Produces a TypeScript file containing:
//! - Zod schema constants for each input/output type
//! - An oRPC `contract` object matching the Rust handler structure
//! - Type exports (`export type X = z.infer<typeof XSchema>`)
//!
//! This crate is pure functions — no Axum, no proc-macros, fully testable.

pub mod contract;
pub mod typescript;

use std::path::Path;

/// Metadata for a single handler, passed in from `orpc::generate_contract()`.
///
/// Mirrors `orpc::HandlerMetadata` but owned (for codegen use).
#[derive(Debug, Clone)]
pub struct HandlerInfo {
    pub name: &'static str,
    pub method: &'static str,
    pub path: &'static str,
    pub input_type_name: &'static str,
    pub output_type_name: &'static str,
    pub module_path: &'static str,
}

/// Builder for TypeScript contract generation.
///
/// # Example
///
/// ```rust,ignore
/// ContractBuilder::new(handlers)
///     .output("../client/src/rpc/index.ts")
///     .unwrap();
/// ```
pub struct ContractBuilder {
    handlers: Vec<HandlerInfo>,
}

impl ContractBuilder {
    pub fn new(handlers: Vec<HandlerInfo>) -> Self {
        Self { handlers }
    }

    /// Generate the TypeScript contract and write it to `path`.
    ///
    /// Rejects paths containing `..` components to prevent path traversal.
    pub fn output(self, path: impl AsRef<Path>) -> std::io::Result<()> {
        let path = path.as_ref();

        // Security: reject path traversal (A03)
        for component in path.components() {
            if component.as_os_str() == ".." {
                return Err(std::io::Error::new(
                    std::io::ErrorKind::InvalidInput,
                    "output path must not contain '..' components",
                ));
            }
        }

        let content = self.generate();

        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }

        std::fs::write(path, content)
    }

    /// Generate the full TypeScript content as a string.
    pub fn generate(self) -> String {
        let schemas = typescript::generate_schemas(&self.handlers);
        let contract = contract::generate_contract(&self.handlers);

        format!(
            "// AUTO-GENERATED by orpc — do not edit manually.\n// Re-generate with: orpc::generate_contract().output(path)\n\n{schemas}\n\n{contract}"
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_handler(name: &'static str, method: &'static str, path: &'static str) -> HandlerInfo {
        HandlerInfo {
            name,
            method,
            path,
            input_type_name: "()",
            output_type_name: "String",
            module_path: "test::handlers",
        }
    }

    #[test]
    fn rejects_path_traversal() {
        let builder = ContractBuilder {
            handlers: vec![make_handler("ping", "GET", "/ping")],
        };
        let result = builder.output("../../../etc/passwd");
        assert!(result.is_err());
        assert!(result.unwrap_err().kind() == std::io::ErrorKind::InvalidInput);
    }

    #[test]
    fn generates_non_empty_content() {
        let builder = ContractBuilder {
            handlers: vec![make_handler("ping", "GET", "/ping")],
        };
        let output = builder.generate();
        assert!(output.contains("AUTO-GENERATED"));
        assert!(output.contains("ping"));
    }
}
